<template>
  <v-dialog
    :model-value="showDisclaimer"
    @update:modelValue="$emit('update:showDisclaimer', $event)"
    fullscreen
  >
    <v-card>
      <v-toolbar color="#002538" dark :height="smAndDown? '96': '64'">
        <v-toolbar-title class="text-h5 text-white px-5 text-uppercase" :style="{ width: smAndDown ? 'auto' : '100%'}">
          Full Disclaimer
        </v-toolbar-title>
        <v-btn icon dark @click="$emit('update:showDisclaimer', false)">
          <v-icon>mdi-close</v-icon>
        </v-btn>
      </v-toolbar>
      <v-card-text class="pa-6 pt-0 html-content disclaimer-content">
        <v-container fluid>
          <h2 class="text-h6 mb-4">Disclaimer for Beta Product Use</h2>
          <p class="mb-4">By using this beta product, you agree to the following terms:</p>

          <h3 class="text-subtitle-1 font-weight-bold mb-2">1. Beta Testing Acknowledgment:</h3>
          <p class="mb-4">This product is currently in beta testing, meaning it is still under development and subject to ongoing improvements. During this phase, the product may contain errors, bugs, or incomplete features, and feedback provided by users will be used to refine and enhance the product. Users should understand that this is not the final version of the product, and changes may occur over time based on feedback and testing results.</p>

          <h3 class="text-subtitle-1 font-weight-bold mb-2">2. Accuracy and Reliability:</h3>
          <p class="mb-4">While we strive to provide accurate and up-to-date information, the responses and content generated by this product may not always be reliable or complete. This product is intended for informational purposes only and is not designed to serve as a sole source of truth or fact. Users are expected to exercise their clinical judgment, verify information with other trusted resources, and make decisions based on a broader context. The product is not a substitute for professional medical, legal, or other regulated advice.</p>

          <h3 class="text-subtitle-1 font-weight-bold mb-2">3. User Responsibility:</h3>
          <p class="mb-4">It is the responsibility of the user to apply their own professional judgment and expertise when using this product. Any decisions made based on the responses generated by the product must be independently verified by the user, and the user should not rely solely on the product for critical decision-making. You agree that you will not hold CPhA, PharmaGuide, or their affiliates, partners, employees, or agents liable for any errors, omissions, or inaccuracies in the information provided by the product.</p>

          <h3 class="text-subtitle-1 font-weight-bold mb-2">4. No Liability:</h3>
          <p class="mb-4">By using this product, you acknowledge and agree that CPhA, PharmaGuide, and their partners or affiliates shall not be liable for any direct, indirect, incidental, consequential, or special damages resulting from the use of this product. This includes, but is not limited to, any decisions made, actions taken, or outcomes experienced as a result of using the product, whether based on error, omission, or inaccuracies in the content or responses provided.</p>

          <h3 class="text-subtitle-1 font-weight-bold mb-2">5. Feedback Collection:</h3>
          <p class="mb-4">During the beta testing phase, CPhA and PharmaGuide may collect data, including user feedback, error reports, and usage patterns, to improve the product. By using this product, you consent to the collection and use of this data for product refinement purposes. Any feedback you provide may be used without compensation or acknowledgment, and you waive any claim to intellectual property rights or compensation for your suggestions.</p>

          <h3 class="text-subtitle-1 font-weight-bold mb-2">6. Acceptance of Full Disclaimer and Terms and Conditions:</h3>
          <p class="mb-4">By using this beta product, you agree to the full Disclaimer, Terms, and Conditions for Use, which govern your access and use of the product. These full terms include important details about liability, warranties, user responsibilities, and intellectual property rights. You can access the full Disclaimer, Terms, and Conditions by clicking the "Disclaimer" link at the bottom of the page.</p>
          <p class="mb-4">Your continued use of the product constitutes your acceptance of these full terms. If you do not agree with the full Disclaimer, Terms, and Conditions, you must immediately stop using the product.</p>

          <h3 class="text-subtitle-1 font-weight-bold mb-2">7. Professional and Legal Use:</h3>
          <p class="mb-4">The information generated by this product should not be interpreted as legal, medical, or professional advice. Users are expected to comply with all applicable laws, regulations, and professional standards when using the product. CPhA and PharmaGuide are not responsible for ensuring that the content or responses generated comply with local laws or professional guidelines.</p>

          <h3 class="text-subtitle-1 font-weight-bold mb-2">8. Modifications and Termination:</h3>
          <p class="mb-4">CPhA and PharmaGuide reserve the right to modify, suspend, or discontinue the beta product at any time without notice. Updates or changes to the product may include changes to its features, functionality, or content. Any changes to the terms of use will be reflected in the full Disclaimer and Terms and Conditions accessible via the link at the bottom of the page. Continued use of the product following such updates constitutes acceptance of the modified terms.</p>
          <p class="mb-4">CPhA and PharmaGuide may also terminate your access to the product without notice if you violate any terms of this disclaimer or the full terms and conditions.</p>

          <h3 class="text-subtitle-1 font-weight-bold mb-2">9. No Warranties:</h3>
          <p class="mb-4">This beta product is provided "as is" and without any warranties, whether express or implied. CPhA and PharmaGuide make no warranties regarding the accuracy, reliability, completeness, or suitability of the product for any particular purpose. All implied warranties, including but not limited to implied warranties of merchantability, fitness for a particular purpose, and non-infringement, are hereby disclaimed to the fullest extent permitted by law.</p>

          <h3 class="text-subtitle-1 font-weight-bold mb-2">10. Entire Agreement:</h3>
          <p class="mb-4">This disclaimer, in conjunction with the full Disclaimer, Terms, and Conditions for Use, constitutes the entire agreement governing your use of this beta product. It supersedes any prior agreements, communications, or understandings, whether oral or written. Any modifications to this agreement must be made in writing and agreed to by both parties. If any part of this agreement is deemed invalid or unenforceable by a court of competent jurisdiction, the remaining provisions will continue in full force and effect.</p>

          <p class="mb-4">By continuing to use this beta product, you confirm that you have read, understood, and agree to this disclaimer and the full Disclaimer, Terms, and Conditions for Use, accessible via the "Disclaimer" link at the bottom of the page. If you do not agree, you must discontinue use immediately.</p>

          <p class="mb-4">If you have any questions or concerns, please contact us at <a href="mailto:support@pharmacists.ca">support@pharmacists.ca</a>.</p>

          <h2 class="text-h6 mb-4">Disclaimer</h2>
          <p class="mb-4">The content on this site is for educational and informational purposes only. The Canadian Pharmacists Association (CPhA) and PharmaGuide make every effort to keep the content current. However, they do not warrant the accuracy, completeness, or timeliness of the information.</p>
          <p class="mb-4">There may be a time lag between the original English text and any translations. CPhA and PharmaGuide do not endorse any organization, product, or therapy.</p>
          <p class="mb-4">The opinions expressed on this site may be AI-generated and do not necessarily reflect the official views or opinions of the content authors, CPhA, PharmaGuide, or Health Canada.</p>

          <h2 class="text-h6 mb-4">Editorial Policy</h2>
          <p class="mb-4">Please consult: CPS Editorial Policy.</p>

          <h2 class="text-h6 mb-4">Copyright and Permissions</h2>
          <p class="mb-4">All information, data, materials, text, audio, video, graphics, charts, photographs, icons, designs, selections, arrangements, documentation, and software, in any medium, contained in or made available through the Service (the "Content") are the property of CPhA, PharmaGuide, and their licensors or providers, and are subject to Canadian copyright and intellectual property laws. You hereby acknowledge that the Service, including, without limitation, the Content, contains proprietary information protected by all applicable copyright, trademark, and other laws. Your use of the Service does not grant or transfer to you any ownership or other rights in the Service, and except as expressly provided, nothing herein or within the Service shall be construed as conferring on you or any other person any license under any of CPhA's, PharmaGuide's, their licensors', providers', or any other third party's intellectual property rights. Reproduction, adaptation, storage, translation, display, distribution, modification, alteration, enhancement, or retransmission of any part of the Service without the express written permission of CPhA and PharmaGuide is prohibited. Limited excerpts of the Content may be used for personal use only, provided that our copyright notice appears with the material in each instance, and such use is consistent with the license below.</p>

          <h2 class="text-h6 mb-4">Copyright Notices of Products</h2>
          <ul class="mb-4">
            <li>CPS Therapeutic Choices. © Canadian Pharmacists Association (CPhA). All rights reserved.</li>
            <li>CPS Drug Information. © Canadian Pharmacists Association (CPhA). All rights reserved.</li>
            <li>CPS Minor Ailments. © Canadian Pharmacists Association (CPhA). All rights reserved.</li>
            <li>CPS Products for Minor Ailments. © Canadian Pharmacists Association (CPhA). All rights reserved.</li>
            <li>Information for the Patient. © Canadian Pharmacists Association (CPhA). All rights reserved.</li>
            <li>CPSgo. © Canadian Pharmacists Association (CPhA). All rights reserved.</li>
            <li>PHOX © Pharmaguide. All rights reserved.</li>
            <li>© Canadian Pharmacists Association (CPhA), All rights reserved.</li>
          </ul>

          <h2 class="text-h6 mb-4">Right to Use</h2>
          <p class="mb-4">Subject to your compliance with these Terms and Conditions, CPhA and PharmaGuide grant you a limited, non-exclusive, non-transferable, non-sublicensable license to access and use the Service, including, without limitation, the Content, solely for your personal and non-commercial use. You acknowledge and agree that you must have a valid subscription to access and use the Service, in accordance with these Terms and Conditions.</p>
          <p class="mb-4">If you experience problems accessing or using the Service, please email <a href="mailto:support@pharmacists.ca">support@pharmacists.ca</a>.</p>

          <h2 class="text-h6 mb-4">Trademarks</h2>
          <p class="mb-4">The names "Canadian Pharmacists Association," "CPhA," "Association des pharmaciens du Canada," "APhC," "CPS,", "CPSgo", "PharmaGuide", "PHOX", and corresponding logos are trademarks of CPhA and PharmaGuide. These marks may not be used without the express written permission of CPhA and PharmaGuide.</p>

          <h2 class="text-h6 mb-4">When to Ask Permission</h2>
          <p class="mb-4">Prior written permission is necessary if you are using the Content in reproductions, adaptations, derivations, or translations.</p>

          <h2 class="text-h6 mb-4">Permission Requests</h2>
          <p class="mb-4">To request permission to use the Content in reproductions, adaptations, derivations, translations, or otherwise outside the scope of the limited license granted herein, complete the Permission Request form (PDF) and return it by email to <a href="mailto:permissions@pharmacists.ca">permissions@pharmacists.ca</a></p>
          <p class="mb-4">For inquiries on the use of the Permission Request form, email: <a href="mailto:permissions@pharmacists.ca">permissions@pharmacists.ca</a></p>

          <h2 class="text-h6 mb-4">Restrictions</h2>
          <p class="mb-4">Title to the Service remains with CPhA, PharmaGuide, their licensors, or their providers. No other right, title, license, or interest in or to the Service, including, without limitation, the Content and/or any other property of CPhA, PharmaGuide, their licensors, or providers is granted to you. Any use of the Service not expressly permitted by these Terms and Conditions is a breach of these Terms and Conditions and may violate copyright, trademark, and other laws.</p>
          <p class="mb-4">This limited license does not include any rights not specifically enumerated herein. Except as expressly authorized by CPhA and PharmaGuide, you agree not to (and not to allow any third party to): (i) modify the Service or create derivative works based on the Service; (ii) reproduce, mirror, duplicate, or copy any portion of the Service or any information obtained from the Service (in whole or in part); (iii) sell, resell, republish, license, transmit, share, reverse engineer, or otherwise make any portion of the Service or any information obtained from the Service available to any third party, whether for instructional, educational, or other purposes; or (iv) use any robot, spider, scraper, or other automated means to access the Service and collect any of the Content or access the Service by any means other than through the interface that is provided by CPhA and PharmaGuide for use in accessing the Service. You shall comply with all applicable law at all times. Content and features are subject to change or termination without notice in the editorial discretion of CPhA and PharmaGuide. All rights not expressly granted herein are reserved by CPhA, PharmaGuide, their licensors, and providers.</p>

          <h2 class="text-h6 mb-4">Term and Termination</h2>
          <p class="mb-4">Subject to these Terms and Conditions, you may continue to access and use the Service as long as you have a valid subscription to the Service.</p>
          <p class="mb-4">If your subscription expires or if you violate any of these Terms and Conditions, your rights under these Terms and Conditions, including any right to access and use the Service, automatically terminate, and you must immediately delete and/or destroy any copies you have made of any portion of the Content. Without limiting the foregoing, CPhA and PharmaGuide may suspend or terminate your use or access to the Service (including by blocking Content or removing downloaded Content) at any time and without notice if you violate these Terms and Conditions. CPhA and PharmaGuide may terminate your use of the Service at any time on written notice.</p>
          <p class="mb-4">Notwithstanding termination of your access and use of the Service, these Terms and Conditions will nevertheless continue to apply and be binding upon you in respect of your prior use of the Service.</p>
          <p class="mb-4">Except as otherwise expressly provided in these Terms and Conditions, if you are dissatisfied with the Service or the Content, then your sole and exclusive remedy is to discontinue accessing and using the Service.</p>

          <h2 class="text-h6 mb-4">Third-Party Sites</h2>
          <p class="mb-4">The Service may link to, or be linked to, sites not maintained by or related to CPhA or PharmaGuide. All links are provided only as a service to our visitors. CPhA and PharmaGuide are not, directly or indirectly, implying any approval, association, sponsorship, endorsement, or affiliation with the linked or linking site, unless specifically stated on the Service. CPhA and PharmaGuide have not reviewed all sites to which they link and are not responsible for the content, accuracy, timeliness, reliability, or policies of any such sites. You link to other pages or sites at your own risk, and your use of other sites will be controlled by the Terms and Conditions posted on those sites. You should review the Terms and Conditions of any site to which you navigate.</p>

          <h2 class="text-h6 mb-4">Privacy Policy</h2>
          <p class="mb-4">By accessing and using the Service, you agree to the terms of our Privacy Policy, which are incorporated into these Terms and Conditions by reference.</p>

          <h2 class="text-h6 mb-4">Software</h2>
          <p class="mb-4">Apple: If you have downloaded software from the Apple iTunes Application Store, the following additional terms apply to such software:</p>
          <p class="mb-4">You agree and acknowledge that these Terms and Conditions are concluded between you and CPhA and PharmaGuide only, and not with Apple, and that Apple is not responsible for the software and its content. In addition, your use of such software downloaded from such location is limited to a non-transferable license to use the software on any Apple-branded products running iOS (including but not limited to iPad, iPhone, and iPod touch) ("iOS Devices") or macOS ("Mac Computers"), as applicable (collectively "Apple Device(s)") that you own or control and as permitted by the Usage Rules set forth in the Apple iTunes Application Store Terms of Service. Moreover, CPhA and PharmaGuide hereby inform you, and you acknowledge and agree that Apple has no obligation whatsoever to furnish any maintenance and support services with respect to the software.</p>
          <p class="mb-4">Apple has no warranty obligation with respect to the software and any claims, losses, liabilities, damages, costs, or expenses attributable to any failure to conform to any warranty set forth in these Terms and Conditions. In the event of any failure of the software to conform to any applicable warranty, you may notify Apple, and Apple will refund the purchase price for the software (if any), and to the maximum extent permitted by law, Apple will have no other warranty obligation whatsoever with respect to the software, and any other claims, losses, liabilities, damages, costs, and expenses attributable to any failure to conform to any warranty will be CPhA's and PharmaGuide's sole responsibility. Please note that to the extent permitted by applicable law, CPhA and PharmaGuide have disclaimed all warranties.</p>
          <p class="mb-4">Apple is not responsible for addressing any claims relating to the software or your possession and/or use of the software, including, but not limited to: (i) product liability claims; (ii) any claim that the software fails to conform to any applicable legal or regulatory requirement; and (iii) claims arising under consumer protection, privacy, or similar legislation.</p>
          <p class="mb-4">Apple is not responsible for any third-party infringement claims that the software or your possession and use of the software infringe a third party's intellectual property rights. In the event of any third-party claim that the software or your possession and use of that software infringes a third party's intellectual property rights, CPhA and PharmaGuide, not Apple, will be solely responsible for the investigation, defense, settlement, and discharge of any such intellectual property infringement claim.</p>
          <p class="mb-4">You acknowledge and agree that Apple, and its subsidiaries, are third-party beneficiaries of these Terms and Conditions and that, upon your acceptance of these Terms and Conditions, Apple will have the right (and will be deemed to have accepted the right) to enforce these Terms and Conditions against you as a third-party beneficiary hereof.</p>
          <p class="mb-4">You represent that you are not located in a country that is subject to a U.S. Government embargo, or that has been designated by the U.S. Government as a "terrorist supporting" country, and that you are not listed on any U.S. Government list of prohibited or restricted parties.</p>

          <h2 class="text-h6 mb-4">Interpretation and Disputes</h2>
          <p class="mb-4">These Terms and Conditions are governed by the laws of the Province of Ontario and the federal laws of Canada applicable therein without regard to any conflict of laws provisions which would have the effect of imposing a different governing law. Forum is exclusively in Ottawa, Ontario, with respect to any dispute arising under these Terms and Conditions unless otherwise agreed by CPhA and PharmaGuide in their sole discretion.</p>
          <p class="mb-4">If any provision of these Terms and Conditions is deemed unenforceable or invalid by a court or arbitrator, then the court or arbitrator may modify such provision to the minimum extent necessary to make an invalid provision enforceable and valid. If modification is impossible or impracticable, then the provision will be severed, and the remaining terms of these Terms and Conditions will be interpreted and read to give them maximum enforceability.</p>

          <h2 class="text-h6 mb-4">Entire Agreement</h2>
          <p class="mb-4">These Terms and Conditions, together with any terms and conditions referenced herein, which are hereby incorporated into and form part of these Terms and Conditions (including, without limitation, CPhA's and PharmaGuide's Privacy Policy, the CPhA Editorial Policy, and Erratum Policy), constitute the entire agreement between you and CPhA and PharmaGuide with respect to your access and use of the Service.</p>
          <p class="mb-4">You are encouraged to review these policies and check periodically for updates.</p>
          <p class="mb-4">These Terms and Conditions are between you, CPhA, and PharmaGuide. Apple Inc. ("Apple"), Google, Inc. ("Google"), and/or their applicable international subsidiaries and affiliates will be third-party beneficiaries to these Terms and Conditions if you access the Service using applications developed for Apple iOS or Android mobile devices, respectively. Apple and Google will have the right (and will be deemed to have accepted the right) to enforce these Terms and Conditions against you as a third-party beneficiary hereof. These third-party beneficiaries are not parties to these Terms and Conditions and are not responsible for the provision or support of the Service in any manner.</p>

          <h2 class="text-h6 mb-4">Waiver</h2>
          <p class="mb-4">Any waiver of any provision of these Terms and Conditions will be effective only if in writing and signed by CPhA and PharmaGuide and only applicable to the specific incident and occurrence so waived. The failure by CPhA and PharmaGuide to insist upon the strict performance of these Terms and Conditions, or to exercise any term hereof, shall not act as a waiver of any right, promise, or term, which shall continue in full force and effect.</p>

          <h2 class="text-h6 mb-4">Assignment</h2>
          <p class="mb-4">These Terms and Conditions may not be assigned by you in whole or in part, without the prior written consent of CPhA and PharmaGuide. Any permitted assignment shall not relieve you of your obligations hereunder. CPhA and PharmaGuide may, without prior notice or consent, assign these Terms and Conditions. You give your approval to CPhA and PharmaGuide for them to assign these Terms and Conditions, in whole or in part, and upon such assignment, the assignee shall assume all the rights and obligations of CPhA and PharmaGuide, and CPhA and PharmaGuide shall be released. These Terms and Conditions will inure to the benefit of CPhA's and PharmaGuide's successors and assigns.</p>

          <h2 class="text-h6 mb-4">Survival</h2>
          <p class="mb-4">The following sections shall survive the termination of these Terms and Conditions or the expiration of your subscription: Disclaimers, Medical Disclaimers, Limitation of Liability, Indemnity, Copyright and Permissions, Trademarks, Restrictions, Termination, Interpretation and Disputes, Entire Agreement, and Survival.</p>

          <h2 class="text-h6 mb-4">Service Agreement</h2>
          <p class="mb-4">The primary subscriber to this subscription has read and accepted the terms and conditions of the following Service Agreement.</p>
          <p class="mb-4">This service agreement (the "Agreement") constitutes the entire agreement between you (the "Client"), and the Canadian Pharmacists Association ("CPhA") and PharmaGuide with respect to the Client's access to and use of CPhA and PharmaGuide's chatbot available online, together with all the information, data, reports, and other information made available to the Client (collectively, the "Service").</p>

          <h2 class="text-h6 mb-4">CPhA and PharmaGuide Policies</h2>
          <p class="mb-4">Client's use of the Service is subject to the CPhA and PharmaGuide Editorial Policy and Erratum Policy, together with any other policies, disclaimers, terms, and conditions posted on the Service, which may be updated by CPhA and PharmaGuide from time to time without notice. The Client is encouraged to check these policies periodically for updates.</p>

          <h2 class="text-h6 mb-4">Payment</h2>
          <p class="mb-4">Client agrees to pay all applicable fees and taxes with respect to the Service that the Client has subscribed for or accessed for the applicable number of users, all in accordance with CPhA and PharmaGuide's then-current fee policy.</p>
          <p class="mb-4">Client shall pay all invoices for fees and taxes on the invoice date. Invoiced fees and taxes are subject to a late payment charge at the rate specified in the invoice, calculated from the invoice date, if not paid within thirty (30) days of the invoice date. Client shall not withhold or deduct any amounts from, or set-off amounts owed by CPhA or PharmaGuide to the Client against, any amounts invoiced by CPhA or PharmaGuide for fees and taxes.</p>

          <h2 class="text-h6 mb-4">Restrictions on Use</h2>
          <p class="mb-4">Client acknowledges and agrees that the Service and any content and software used in connection with the Service contain proprietary information that is protected by applicable intellectual property and other laws. All whole and partial copies of the Service and any information obtained from the Service remain the property of CPhA, PharmaGuide, and their licensors and will be considered part of the Service for purposes of this Agreement.</p>
          <p class="mb-4">Except as expressly authorized by CPhA and PharmaGuide, the Client agrees not to (and will not allow any third party to): (i) modify the Service or create derivative works based on the Service; (ii) reproduce, duplicate or copy any portion of the Service or any information obtained from the Service; (iii) sell, resell, reverse engineer, or otherwise make any portion of the Service or any information obtained from the Service available to any third party; or (vi) access the Service by any means other than through the interface that is provided by CPhA and PharmaGuide for use in accessing the Service.</p>
          <p class="mb-4">Client and its User(s) (as defined in Section 4) are permitted to print a reasonable number of copies of limited portions of the Content solely for the Client's (and its Users') own personal reference. Client and its User(s) are also permitted to print and distribute to Client's (or its Users') own patients a reasonable number of copies of certain items of Content specifically designated as patient information on the Service. In the event that Client wishes to make any use of the Service or Content outside of these restrictions, then Client should contact CPhA and PharmaGuide directly to discuss its requirements.</p>
          <p class="mb-4">Client may, in some circumstances, print selected sections of product monographs; however, CPhA and PharmaGuide recommend that where product monographs are used, the full product monograph should be used. Partial product monographs should not be provided to patients or anyone else and are for use only by Clients, at their own risk. CPhA and PharmaGuide assume no responsibility for, or liability in connection with, the use of partial product monographs obtained from the Service.</p>

          <h2 class="text-h6 mb-4">License Grant</h2>
          <p class="mb-4">Subject to the terms and conditions of this Agreement, CPhA and PharmaGuide grant to the Client a personal, non-exclusive, non-transferable, and limited license for the use of the Service on CPhA and PharmaGuide's web server(s) by one or more of the Client's employees (each a "User") solely for the Client's internal, non-commercial purposes, provided that the Service is used, at any given time, only by as many User(s) as the Client has purchased concurrent licenses. The foregoing license shall be for access and use only by the equivalent number of User(s) for whom the Client has paid the applicable license fees. The Client is not permitted to use, reproduce, transmit, or communicate the Content for instructional or educational purposes. In the event that the Client wishes to use any Content for instructional or educational purposes, the Client must contact CPhA and PharmaGuide to discuss its requirements.</p>
          <p class="mb-4">No other right, title, license, or interest in or to the Service and/or any other property of CPhA, PharmaGuide, or their licensors is hereby granted to the Client. CPhA and PharmaGuide may make changes to the Service at any time and without notice.</p>

          <h2 class="text-h6 mb-4">Access to Service</h2>
          <p class="mb-4">Username and Password. The Client shall obtain a username ("Username") and password ("Password") from CPhA and PharmaGuide, which shall be used by the Client's User(s) to access the Service. The Client acknowledges and agrees that it: i. has ensured that any of the Client's User(s) accessing the Service understand the privacy, confidentiality, and security terms outlined in this Agreement, including, but not limited to, the requirement to exit from the account at the end of each session; and ii. shall ensure that all User(s) of the Service are aware of the Client's obligations under this Agreement.</p>
          <p class="mb-4">Multiple Users - Primary Contact Information. If the Client has more than one User, the Client shall designate an employee as its primary contact for purposes of this Agreement (the "Primary Contact"). The Client shall inform CPhA and PharmaGuide of the identity of its Primary Contact and shall provide true, accurate, current, and complete information with respect to the Primary Contact. The Client agrees to maintain and promptly update such information as may be required from time to time, to keep it true, accurate, current, and complete. CPhA and PharmaGuide will use such information for purposes of managing access to the system and advising the Client of relevant products and services related to the Service.</p>
          <p class="mb-4">Individual Users - User Information. If the Client has only one User, the Client shall provide true, accurate, current, and complete information with respect to such User. The Client agrees to maintain and promptly update such information as may be required from time to time, to keep it true, accurate, current, and complete. CPhA and PharmaGuide will use such information for purposes of managing access to the system and advising the Client of relevant products and services related to the Service.</p>

          <h2 class="text-h6 mb-4">Confidential Information</h2>
          <p class="mb-4">Except as otherwise required by applicable law, the Client, its employees, contractors, and each of its User(s) shall maintain all Confidential Information obtained in connection with this Agreement in strict confidence.</p>
          <p class="mb-4">For purposes of this Agreement, "Confidential Information" means all data and information which the Client and any User(s) have obtained as a result of using the Service and which is marked confidential, including without limitation, any Username and Password.</p>

          <h2 class="text-h6 mb-4">Disclaimer of Warranties, Limitation of Liability</h2>
          <p class="mb-4">EXCEPT AS EXPRESSLY PROVIDED HEREIN, THE SERVICE IS PROVIDED ON AN "AS IS" AND "AS AVAILABLE" BASIS WITHOUT OTHER WARRANTIES OR CONDITIONS OF ANY KIND, INCLUDING BUT NOT LIMITED TO IMPLIED WARRANTIES OR CONDITIONS OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, AND NONINFRINGEMENT. ALL IMPLIED WARRANTIES ARE HEREBY EXPRESSLY DISCLAIMED BY CPhA, PHARMAGUIDE, AND WAIVED BY THE CLIENT. THE ENTIRE RISK AS TO THE ACCURACY OF ANY INFORMATION ON THE SERVICE AND USE OF THE SERVICE, AND THE RESULTS AND PERFORMANCE OF THE SERVICE, ARE ASSUMED BY THE CLIENT. THE CLIENT ACKNOWLEDGES AND AGREES THAT THE INFORMATION AVAILABLE ON THE SERVICE IS NOT EXHAUSTIVE AND IS NOT INTENDED TO BE ALL-INCLUSIVE. CPhA AND PHARMAGUIDE ARE NOT RESPONSIBLE FOR ANY ERRORS OR OMISSIONS THEREIN.</p>

          <p class="mb-4">YOU ACCEPT AND AGREE THAT ANY USE OF OUTPUTS FROM OUR SERVICE IS AT YOUR SOLE RISK AND YOU WILL NOT RELY ON OUTPUT AS A SOLE SOURCE OF TRUTH OR FACTUAL INFORMATION, OR AS A SUBSTITUTE FOR PROFESSIONAL ADVICE.</p>

          <p class="mb-4">IN NO EVENT SHALL CPhA, PHARMAGUIDE, OR THEIR LICENSORS, AGENTS, SUPPLIERS, OR SUBCONTRACTORS BE LIABLE FOR ANY INDIRECT, CONSEQUENTIAL, INCIDENTAL, SPECIAL, OR OTHER SIMILAR DAMAGES, THAT MAY ARISE UNDER OR IN CONNECTION WITH THIS AGREEMENT, HOWSOEVER CAUSED, INCLUDING WITHOUT LIMITATION, LOST PROFITS OR LOSS OF REVENUE, WHETHER ARISING IN NEGLIGENCE, TORT, STATUTE, EQUITY, CONTRACT (INCLUDING FUNDAMENTAL BREACH), COMMON LAW, OR ANY OTHER CAUSE OF ACTION OR LEGAL THEORY, EVEN IF ADVISED OF THE POSSIBILITY OF THOSE DAMAGES.</p>

          <p class="mb-4">IN NO EVENT, WHETHER ARISING IN NEGLIGENCE, TORT, STATUTE, EQUITY, CONTRACT (INCLUDING FUNDAMENTAL BREACH), COMMON LAW, OR ANY OTHER CAUSE OF ACTION OR LEGAL THEORY, EVEN IF ADVISED OF THE POSSIBILITY OF THOSE DAMAGES, SHALL CPhA'S AND PHARMAGUIDE'S TOTAL LIABILITY TO THE CLIENT FOR ANY DAMAGES, LOSSES, CAUSES OF ACTION, OR OTHER AMOUNTS UNDER OR ARISING OUT OF OR IN CONNECTION WITH THIS AGREEMENT EXCEED THE AMOUNT PAID BY THE CLIENT TO CPhA AND PHARMAGUIDE FOR THE SERVICES PROVIDED HEREUNDER IN THE TWO (2) MONTHS IMMEDIATELY PRECEDING THE EVENT GIVING RISE TO THE CLAIM.</p>

          <p class="mb-4">CPhA, PHARMAGUIDE, AND THEIR LICENSORS, AGENTS, SUPPLIERS, AND SUBCONTRACTORS ARE NOT LIABLE FOR, AND THE CLIENT SHALL BE LIABLE FOR: (I) THE CLIENT'S AND ITS USERS' USE OF THE SERVICE OR TRANSMISSION OF THE CONTENT; AND (II) CLAIMS AGAINST CPhA, PHARMAGUIDE, AND THEIR LICENSORS, AGENTS, SUPPLIERS, AND SUBCONTRACTORS BY USER(S) IN CONNECTION WITH THE SERVICE.</p>

          <p class="mb-4">The Client acknowledges and agrees that the Service may be unavailable periodically for scheduled and unscheduled maintenance. CPhA and PharmaGuide will endeavor to provide notice of any scheduled maintenance periods. CPhA and PharmaGuide will endeavor to perform scheduled maintenance during off-peak hours, provided that in certain circumstances, scheduled maintenance may need to be performed during business hours.</p>

          <h2 class="text-h6 mb-4">Term and Termination</h2>
          <p class="mb-4">The term of this Agreement shall begin on the date of acceptance of this Agreement by the Client and shall end when terminated by the Client or by CPhA and PharmaGuide.</p>

          <p class="mb-4">CPhA and PharmaGuide may immediately terminate this Agreement and/or any User's access to the Service if the Client or any User has breached the Agreement.</p>

          <p class="mb-4">The Client may terminate this Agreement at any time by ceasing to use the Service. If the Client notifies CPhA and PharmaGuide in writing of its termination of this Agreement within fourteen (14) days of the date of the Client's acceptance of this Agreement, then the Client shall be entitled to receive a refund of any prepaid fees less an administrative fee of fifty dollars ($50.00). Except as set out in Section 11 below, CPhA and PharmaGuide will not provide a refund of any fees paid by the Client if the Client terminates this Agreement after fourteen (14) days from the date of the Client's acceptance of this Agreement.</p>

          <p class="mb-4">CPhA and PharmaGuide may terminate this Agreement, for convenience, at any time, by providing the Client with not less than thirty (30) days written notice. In the event that CPhA and PharmaGuide terminate the agreement for convenience pursuant to this paragraph, then they shall refund to the Client a pro rata portion of any amounts paid by the Client in advance with respect to Services to be provided after the effective date of termination.</p>

          <h2 class="text-h6 mb-4">Member Account, Password, and Security</h2>
          <p class="mb-4">The Client and its User(s) are responsible for maintaining the confidentiality of all means of access to the Service. The Client is fully responsible for all activities that occur under the Client's means of access.</p>

          <p class="mb-4">The Client agrees to immediately notify CPhA and PharmaGuide of any unauthorized use of any of the Client's means of access or any other breach of confidentiality or security.</p>

          <h2 class="text-h6 mb-4">Indemnity</h2>
          <p class="mb-4">The Client shall defend, indemnify, and hold CPhA, PharmaGuide, and their officers, directors, employees, licensors, agents, suppliers, and subcontractors harmless from any loss, debt, liability, damage, obligation, claim, demand, judgment, or settlement of any nature or kind, including reasonable legal fees, made by any third party due to or arising out of, or in connection with, the Client's use of the Service, or any of the Client's employees or Users' use of the Service, the Client's connection to the Service, or any breach of this Agreement.</p>

          <h2 class="text-h6 mb-4">General</h2>
          <p class="mb-4">CPhA and PharmaGuide may update and change this Agreement from time to time. The most recent version of this Agreement shall be available at <a href="https://pharmachat.app">https://pharmachat.app</a>. The Agreement shall be governed by the laws in force in the Province of Ontario, Canada without regard to conflict of laws. Any dispute that may arise under this Agreement shall be resolved in the Province of Ontario in the City of Ottawa. If any provision hereof is held by a court of competent jurisdiction to be invalid, it shall be severed, and the remaining provisions shall remain in full force without being invalidated in any way. The parties hereto are independent contractors. This Agreement and any additional terms are not intended to create a partnership, joint venture, or agency relationship between the parties. This is the entire agreement between the Client and CPhA and PharmaGuide relating to the matters contained herein and shall not be modified except in writing by CPhA and PharmaGuide. This Agreement may not be assigned without CPhA and PharmaGuide's written permission. No party will be deemed to have waived the exercise of any right unless such waiver is in writing. Sections 3, 6, 7, 10, and 11 shall survive termination of this Agreement.</p>
        </v-container>
      </v-card-text>
    </v-card>
  </v-dialog>
</template>

<script setup>
import { useDisplay } from 'vuetify';

defineProps({
  showDisclaimer: {
    type: Boolean,
    required: true
  }
});

const { smAndDown } = useDisplay();
defineEmits(['update:showDisclaimer']);
</script>

<style lang="scss" scoped>
.v-card-title {
  padding: 16px;
}

.terms-dialog {
  .terms-content {
    overflow-y: auto;
  }

  a {
    color: #52B8C5;
    text-decoration: none;
  }

  a:hover {
    text-decoration: underline;
  }
}

:deep(.v-toolbar-title__placeholder) {
  text-wrap: auto !important;
  white-space: normal;
}
</style>
