"use client";

import { useEffect, useState } from "react";

interface DisclaimerDialogProps {
  isOpen: boolean;
  onClose: () => void;
}

export function DisclaimerDialog({ isOpen, onClose }: DisclaimerDialogProps) {
  const [isMobile, setIsMobile] = useState(false);

  useEffect(() => {
    const checkMobile = () => setIsMobile(window.innerWidth < 640);
    checkMobile();
    window.addEventListener("resize", checkMobile);
    return () => window.removeEventListener("resize", checkMobile);
  }, []);

  useEffect(() => {
    // Prevent body scroll when dialog is open
    if (isOpen) {
      document.body.style.overflow = "hidden";
    } else {
      document.body.style.overflow = "";
    }
    return () => {
      document.body.style.overflow = "";
    };
  }, [isOpen]);

  if (!isOpen) return null;

  const linkStyle = { color: "#52B8C5" };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/50">
      <div className="flex h-full w-full flex-col bg-white">
        {/* Header */}
        <div
          className={`flex items-center justify-between px-6 text-white ${
            isMobile ? "py-6" : "py-4"
          }`}
          style={{ backgroundColor: "#002538" }}
        >
          <h2 className="text-xl font-semibold uppercase">Full Disclaimer</h2>
          <button
            onClick={onClose}
            className="flex h-10 w-10 items-center justify-center rounded-full transition-colors hover:bg-white/10"
            aria-label="Close disclaimer"
          >
            <svg
              viewBox="0 0 24 24"
              fill="none"
              stroke="currentColor"
              strokeWidth="2"
              strokeLinecap="round"
              strokeLinejoin="round"
              className="h-6 w-6"
            >
              <line x1="18" y1="6" x2="6" y2="18" />
              <line x1="6" y1="6" x2="18" y2="18" />
            </svg>
          </button>
        </div>

        {/* Content */}
        <div className="flex-1 overflow-y-auto px-6 py-6 text-slate-700">
          <div className="mx-auto max-w-4xl space-y-6">
            <section>
              <h2 className="mb-4 text-xl font-bold text-slate-900">
                Disclaimer for Beta Product Use
              </h2>
              <p className="mb-4 text-sm leading-relaxed">
                By using this beta product, you agree to the following terms:
              </p>
            </section>

            <section>
              <h3 className="mb-3 text-base font-bold text-slate-900">
                1. Beta Testing Acknowledgment:
              </h3>
              <p className="mb-4 text-sm leading-relaxed">
                This product is currently in beta testing, meaning it is still under development and subject to ongoing improvements. During this phase, the product may contain errors, bugs, or incomplete features, and feedback provided by users will be used to refine and enhance the product. Users should understand that this is not the final version of the product, and changes may occur over time based on feedback and testing results.
              </p>
            </section>

            <section>
              <h3 className="mb-3 text-base font-bold text-slate-900">
                2. Accuracy and Reliability:
              </h3>
              <p className="mb-4 text-sm leading-relaxed">
                While we strive to provide accurate and up-to-date information, the responses and content generated by this product may not always be reliable or complete. This product is intended for informational purposes only and is not designed to serve as a sole source of truth or fact. Users are expected to exercise their clinical judgment, verify information with other trusted resources, and make decisions based on a broader context. The product is not a substitute for professional medical, legal, or other regulated advice.
              </p>
            </section>

            <section>
              <h3 className="mb-3 text-base font-bold text-slate-900">
                3. User Responsibility:
              </h3>
              <p className="mb-4 text-sm leading-relaxed">
                It is the responsibility of the user to apply their own professional judgment and expertise when using this product. Any decisions made based on the responses generated by the product must be independently verified by the user, and the user should not rely solely on the product for critical decision-making. You agree that you will not hold CPhA, PharmaGuide, or their affiliates, partners, employees, or agents liable for any errors, omissions, or inaccuracies in the information provided by the product.
              </p>
            </section>

            <section>
              <h3 className="mb-3 text-base font-bold text-slate-900">
                4. No Liability:
              </h3>
              <p className="mb-4 text-sm leading-relaxed">
                By using this product, you acknowledge and agree that CPhA, PharmaGuide, and their partners or affiliates shall not be liable for any direct, indirect, incidental, consequential, or special damages resulting from the use of this product. This includes, but is not limited to, any decisions made, actions taken, or outcomes experienced as a result of using the product, whether based on error, omission, or inaccuracies in the content or responses provided.
              </p>
            </section>

            <section>
              <h3 className="mb-3 text-base font-bold text-slate-900">
                5. Feedback Collection:
              </h3>
              <p className="mb-4 text-sm leading-relaxed">
                During the beta testing phase, CPhA and PharmaGuide may collect data, including user feedback, error reports, and usage patterns, to improve the product. By using this product, you consent to the collection and use of this data for product refinement purposes. Any feedback you provide may be used without compensation or acknowledgment, and you waive any claim to intellectual property rights or compensation for your suggestions.
              </p>
            </section>

            <section>
              <h3 className="mb-3 text-base font-bold text-slate-900">
                6. Acceptance of Full Disclaimer and Terms and Conditions:
              </h3>
              <p className="mb-4 text-sm leading-relaxed">
                By using this beta product, you agree to the full Disclaimer, Terms, and Conditions for Use, which govern your access and use of the product. These full terms include important details about liability, warranties, user responsibilities, and intellectual property rights. You can access the full Disclaimer, Terms, and Conditions by clicking the &quot;Disclaimer&quot; link at the bottom of the page.
              </p>
              <p className="mb-4 text-sm leading-relaxed">
                Your continued use of the product constitutes your acceptance of these full terms. If you do not agree with the full Disclaimer, Terms, and Conditions, you must immediately stop using the product.
              </p>
            </section>

            <section>
              <h3 className="mb-3 text-base font-bold text-slate-900">
                7. Professional and Legal Use:
              </h3>
              <p className="mb-4 text-sm leading-relaxed">
                The information generated by this product should not be interpreted as legal, medical, or professional advice. Users are expected to comply with all applicable laws, regulations, and professional standards when using the product. CPhA and PharmaGuide are not responsible for ensuring that the content or responses generated comply with local laws or professional guidelines.
              </p>
            </section>

            <section>
              <h3 className="mb-3 text-base font-bold text-slate-900">
                8. Modifications and Termination:
              </h3>
              <p className="mb-4 text-sm leading-relaxed">
                CPhA and PharmaGuide reserve the right to modify, suspend, or discontinue the beta product at any time without notice. Updates or changes to the product may include changes to its features, functionality, or content. Any changes to the terms of use will be reflected in the full Disclaimer and Terms and Conditions accessible via the link at the bottom of the page. Continued use of the product following such updates constitutes acceptance of the modified terms.
              </p>
              <p className="mb-4 text-sm leading-relaxed">
                CPhA and PharmaGuide may also terminate your access to the product without notice if you violate any terms of this disclaimer or the full terms and conditions.
              </p>
            </section>

            <section>
              <h3 className="mb-3 text-base font-bold text-slate-900">
                9. No Warranties:
              </h3>
              <p className="mb-4 text-sm leading-relaxed">
                This beta product is provided &quot;as is&quot; and without any warranties, whether express or implied. CPhA and PharmaGuide make no warranties regarding the accuracy, reliability, completeness, or suitability of the product for any particular purpose. All implied warranties, including but not limited to implied warranties of merchantability, fitness for a particular purpose, and non-infringement, are hereby disclaimed to the fullest extent permitted by law.
              </p>
            </section>

            <section>
              <h3 className="mb-3 text-base font-bold text-slate-900">
                10. Entire Agreement:
              </h3>
              <p className="mb-4 text-sm leading-relaxed">
                This disclaimer, in conjunction with the full Disclaimer, Terms, and Conditions for Use, constitutes the entire agreement governing your use of this beta product. It supersedes any prior agreements, communications, or understandings, whether oral or written. Any modifications to this agreement must be made in writing and agreed to by both parties. If any part of this agreement is deemed invalid or unenforceable by a court of competent jurisdiction, the remaining provisions will continue in full force and effect.
              </p>
              <p className="mb-4 text-sm leading-relaxed">
                By continuing to use this beta product, you confirm that you have read, understood, and agree to this disclaimer and the full Disclaimer, Terms, and Conditions for Use, accessible via the &quot;Disclaimer&quot; link at the bottom of the page. If you do not agree, you must discontinue use immediately.
              </p>
              <p className="mb-4 text-sm leading-relaxed">
                If you have any questions or concerns, please contact us at{" "}
                <a
                  href="mailto:support@pharmacists.ca"
                  className="underline hover:no-underline"
                  style={linkStyle}
                >
                  support@pharmacists.ca
                </a>
                .
              </p>
            </section>

            <section>
              <h2 className="mb-4 text-xl font-bold text-slate-900">
                Disclaimer
              </h2>
              <p className="mb-4 text-sm leading-relaxed">
                The content on this site is for educational and informational purposes only. The Canadian Pharmacists Association (CPhA) and PharmaGuide make every effort to keep the content current. However, they do not warrant the accuracy, completeness, or timeliness of the information.
              </p>
              <p className="mb-4 text-sm leading-relaxed">
                There may be a time lag between the original English text and any translations. CPhA and PharmaGuide do not endorse any organization, product, or therapy.
              </p>
              <p className="mb-4 text-sm leading-relaxed">
                The opinions expressed on this site may be AI-generated and do not necessarily reflect the official views or opinions of the content authors, CPhA, PharmaGuide, or Health Canada.
              </p>
            </section>

            <section>
              <h2 className="mb-4 text-xl font-bold text-slate-900">
                Editorial Policy
              </h2>
              <p className="mb-4 text-sm leading-relaxed">
                Please consult: CPS Editorial Policy.
              </p>
            </section>

            <section>
              <h2 className="mb-4 text-xl font-bold text-slate-900">
                Copyright and Permissions
              </h2>
              <p className="mb-4 text-sm leading-relaxed">
                All information, data, materials, text, audio, video, graphics, charts, photographs, icons, designs, selections, arrangements, documentation, and software, in any medium, contained in or made available through the Service (the &quot;Content&quot;) are the property of CPhA, PharmaGuide, and their licensors or providers, and are subject to Canadian copyright and intellectual property laws. You hereby acknowledge that the Service, including, without limitation, the Content, contains proprietary information protected by all applicable copyright, trademark, and other laws. Your use of the Service does not grant or transfer to you any ownership or other rights in the Service, and except as expressly provided, nothing herein or within the Service shall be construed as conferring on you or any other person any license under any of CPhA&apos;s, PharmaGuide&apos;s, their licensors&apos;, providers&apos;, or any other third party&apos;s intellectual property rights. Reproduction, adaptation, storage, translation, display, distribution, modification, alteration, enhancement, or retransmission of any part of the Service without the express written permission of CPhA and PharmaGuide is prohibited. Limited excerpts of the Content may be used for personal use only, provided that our copyright notice appears with the material in each instance, and such use is consistent with the license below.
              </p>
            </section>

            <section>
              <h2 className="mb-4 text-xl font-bold text-slate-900">
                Copyright Notices of Products
              </h2>
              <ul className="mb-4 list-disc space-y-2 pl-6 text-sm">
                <li>CPS Therapeutic Choices. © Canadian Pharmacists Association (CPhA). All rights reserved.</li>
                <li>CPS Drug Information. © Canadian Pharmacists Association (CPhA). All rights reserved.</li>
                <li>CPS Minor Ailments. © Canadian Pharmacists Association (CPhA). All rights reserved.</li>
                <li>CPS Products for Minor Ailments. © Canadian Pharmacists Association (CPhA). All rights reserved.</li>
                <li>Information for the Patient. © Canadian Pharmacists Association (CPhA). All rights reserved.</li>
                <li>CPSgo. © Canadian Pharmacists Association (CPhA). All rights reserved.</li>
                <li>PHOX © Pharmaguide. All rights reserved.</li>
                <li>© Canadian Pharmacists Association (CPhA), All rights reserved.</li>
              </ul>
            </section>

            <section>
              <h2 className="mb-4 text-xl font-bold text-slate-900">
                Right to Use
              </h2>
              <p className="mb-4 text-sm leading-relaxed">
                Subject to your compliance with these Terms and Conditions, CPhA and PharmaGuide grant you a limited, non-exclusive, non-transferable, non-sublicensable license to access and use the Service, including, without limitation, the Content, solely for your personal and non-commercial use. You acknowledge and agree that you must have a valid subscription to access and use the Service, in accordance with these Terms and Conditions.
              </p>
              <p className="mb-4 text-sm leading-relaxed">
                If you experience problems accessing or using the Service, please email{" "}
                <a
                  href="mailto:support@pharmacists.ca"
                  className="underline hover:no-underline"
                  style={linkStyle}
                >
                  support@pharmacists.ca
                </a>
                .
              </p>
            </section>

            <section>
              <h2 className="mb-4 text-xl font-bold text-slate-900">
                Trademarks
              </h2>
              <p className="mb-4 text-sm leading-relaxed">
                The names &quot;Canadian Pharmacists Association,&quot; &quot;CPhA,&quot; &quot;Association des pharmaciens du Canada,&quot; &quot;APhC,&quot; &quot;CPS,&quot;, &quot;CPSgo&quot;, &quot;PharmaGuide&quot;, &quot;PHOX&quot;, and corresponding logos are trademarks of CPhA and PharmaGuide. These marks may not be used without the express written permission of CPhA and PharmaGuide.
              </p>
            </section>

            <section>
              <h2 className="mb-4 text-xl font-bold text-slate-900">
                When to Ask Permission
              </h2>
              <p className="mb-4 text-sm leading-relaxed">
                Prior written permission is necessary if you are using the Content in reproductions, adaptations, derivations, or translations.
              </p>
            </section>

            <section>
              <h2 className="mb-4 text-xl font-bold text-slate-900">
                Permission Requests
              </h2>
              <p className="mb-4 text-sm leading-relaxed">
                To request permission to use the Content in reproductions, adaptations, derivations, translations, or otherwise outside the scope of the limited license granted herein, complete the Permission Request form (PDF) and return it by email to{" "}
                <a
                  href="mailto:permissions@pharmacists.ca"
                  className="underline hover:no-underline"
                  style={linkStyle}
                >
                  permissions@pharmacists.ca
                </a>
              </p>
              <p className="mb-4 text-sm leading-relaxed">
                For inquiries on the use of the Permission Request form, email:{" "}
                <a
                  href="mailto:permissions@pharmacists.ca"
                  className="underline hover:no-underline"
                  style={linkStyle}
                >
                  permissions@pharmacists.ca
                </a>
              </p>
            </section>

            <section>
              <h2 className="mb-4 text-xl font-bold text-slate-900">
                Restrictions
              </h2>
              <p className="mb-4 text-sm leading-relaxed">
                Title to the Service remains with CPhA, PharmaGuide, their licensors, or their providers. No other right, title, license, or interest in or to the Service, including, without limitation, the Content and/or any other property of CPhA, PharmaGuide, their licensors, or providers is granted to you. Any use of the Service not expressly permitted by these Terms and Conditions is a breach of these Terms and Conditions and may violate copyright, trademark, and other laws.
              </p>
              <p className="mb-4 text-sm leading-relaxed">
                This limited license does not include any rights not specifically enumerated herein. Except as expressly authorized by CPhA and PharmaGuide, you agree not to (and not to allow any third party to): (i) modify the Service or create derivative works based on the Service; (ii) reproduce, mirror, duplicate, or copy any portion of the Service or any information obtained from the Service (in whole or in part); (iii) sell, resell, republish, license, transmit, share, reverse engineer, or otherwise make any portion of the Service or any information obtained from the Service available to any third party, whether for instructional, educational, or other purposes; or (iv) use any robot, spider, scraper, or other automated means to access the Service and collect any of the Content or access the Service by any means other than through the interface that is provided by CPhA and PharmaGuide for use in accessing the Service. You shall comply with all applicable law at all times. Content and features are subject to change or termination without notice in the editorial discretion of CPhA and PharmaGuide. All rights not expressly granted herein are reserved by CPhA, PharmaGuide, their licensors, and providers.
              </p>
            </section>

            {/* Continue with remaining sections - this is getting very long, so I'll add the key remaining sections */}
            
            <section>
              <h2 className="mb-4 text-xl font-bold text-slate-900">
                Term and Termination
              </h2>
              <p className="mb-4 text-sm leading-relaxed">
                Subject to these Terms and Conditions, you may continue to access and use the Service as long as you have a valid subscription to the Service.
              </p>
              <p className="mb-4 text-sm leading-relaxed">
                If your subscription expires or if you violate any of these Terms and Conditions, your rights under these Terms and Conditions, including any right to access and use the Service, automatically terminate, and you must immediately delete and/or destroy any copies you have made of any portion of the Content. Without limiting the foregoing, CPhA and PharmaGuide may suspend or terminate your use or access to the Service (including by blocking Content or removing downloaded Content) at any time and without notice if you violate these Terms and Conditions. CPhA and PharmaGuide may terminate your use of the Service at any time on written notice.
              </p>
              <p className="mb-4 text-sm leading-relaxed">
                Notwithstanding termination of your access and use of the Service, these Terms and Conditions will nevertheless continue to apply and be binding upon you in respect of your prior use of the Service.
              </p>
              <p className="mb-4 text-sm leading-relaxed">
                Except as otherwise expressly provided in these Terms and Conditions, if you are dissatisfied with the Service or the Content, then your sole and exclusive remedy is to discontinue accessing and using the Service.
              </p>
            </section>

            <section>
              <h2 className="mb-4 text-xl font-bold text-slate-900">
                Third-Party Sites
              </h2>
              <p className="mb-4 text-sm leading-relaxed">
                The Service may link to, or be linked to, sites not maintained by or related to CPhA or PharmaGuide. All links are provided only as a service to our visitors. CPhA and PharmaGuide are not, directly or indirectly, implying any approval, association, sponsorship, endorsement, or affiliation with the linked or linking site, unless specifically stated on the Service. CPhA and PharmaGuide have not reviewed all sites to which they link and are not responsible for the content, accuracy, timeliness, reliability, or policies of any such sites. You link to other pages or sites at your own risk, and your use of other sites will be controlled by the Terms and Conditions posted on those sites. You should review the Terms and Conditions of any site to which you navigate.
              </p>
            </section>

            <section>
              <h2 className="mb-4 text-xl font-bold text-slate-900">
                Privacy Policy
              </h2>
              <p className="mb-4 text-sm leading-relaxed">
                By accessing and using the Service, you agree to the terms of our Privacy Policy, which are incorporated into these Terms and Conditions by reference.
              </p>
            </section>

            <div className="mt-8 border-t border-slate-200 pt-6">
              <p className="text-xs text-slate-500">
                Last updated: {new Date().toLocaleDateString()}
              </p>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
